# Generated by Django 4.1.2 on 2022-11-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dclientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('tipo', models.CharField(choices=[('F', 'Pessoa Física'), ('P', 'Pessoa Jurídica')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dproduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomep', models.CharField(max_length=20)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dpedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField()),
                ('valor_pedido', models.FloatField()),
                ('status', models.DateField(choices=[('PP', 'pedido em processo'), ('PR', 'pedido realizado'), ('PE', 'pedido entregue')], max_length=2)),
                ('quantidade_pedido', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.dclientes')),
            ],
        ),
    ]
