# Generated by Django 4.1.2 on 2022-11-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0002_alter_dpedidos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpedidos',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cadastre.dproduto'),
            preserve_default=False,
        ),
    ]
